import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { AccountProfile } from '../models/AccountProfile';
import { CommandExecutor } from '../utils/commandExecutor';
import { Logger } from '../utils/logger';

export class SSHAuthStrategy {
    private get sshConfigPath(): string {
        return path.join(os.homedir(), '.ssh', 'config');
    }

    /**
     * Ensures an OpenSSH Host Alias entry exists in ~/.ssh/config for the account profile.
     */
    public async ensureSSHHostAlias(profile: AccountProfile): Promise<string> {
        const hostAlias = profile.sshProfileHostAlias || `github.com-${profile.githubUsername}`;
        const keyPath = profile.sshKeyPath || path.join(os.homedir(), '.ssh', `id_ed25519_${profile.githubUsername}`);

        const configDir = path.join(os.homedir(), '.ssh');
        if (!fs.existsSync(configDir)) {
            fs.mkdirSync(configDir, { recursive: true, mode: 0o700 });
        }

        let currentConfig = '';
        if (fs.existsSync(this.sshConfigPath)) {
            currentConfig = fs.readFileSync(this.sshConfigPath, 'utf8');
        }

        // Check if Host block already exists
        const hostRegex = new RegExp(`^Host\\s+${hostAlias}\\b`, 'm');
        if (!hostRegex.test(currentConfig)) {
            const hostBlock = `\n# Generated by GitHub Account Manager for profile: ${profile.displayName}\n` +
                `Host ${hostAlias}\n` +
                `    HostName github.com\n` +
                `    User git\n` +
                `    IdentityFile ${keyPath.replace(/\\/g, '/')}\n` +
                `    IdentitiesOnly yes\n`;

            fs.appendFileSync(this.sshConfigPath, hostBlock, { mode: 0o600 });
            Logger.info(`Added OpenSSH host alias '${hostAlias}' to ${this.sshConfigPath}`);
        }

        return hostAlias;
    }

    /**
     * Binds a repository's SSH remote URL to use the designated Host Alias.
     * Example: git@github.com:company/app.git -> git@github.com-work:company/app.git
     */
    public async bindRepoRemoteToHostAlias(repoPath: string, hostAlias: string): Promise<boolean> {
        try {
            const getUrlRes = await CommandExecutor.execute('git', ['remote', 'get-url', 'origin'], { cwd: repoPath });
            if (getUrlRes.exitCode !== 0 || !getUrlRes.stdout) return false;

            const currentUrl = getUrlRes.stdout.trim();
            const sshMatch = currentUrl.match(/^git@([^:]+):([^/]+\/.+?\.git)$/);

            if (sshMatch) {
                const newUrl = `git@${hostAlias}:${sshMatch[2]}`;
                if (currentUrl !== newUrl) {
                    const setUrlRes = await CommandExecutor.execute('git', ['remote', 'set-url', 'origin', newUrl], { cwd: repoPath });
                    if (setUrlRes.exitCode === 0) {
                        Logger.info(`Updated repository remote URL from '${currentUrl}' to '${newUrl}'`);
                        return true;
                    }
                }
            }
            return true;
        } catch (error) {
            Logger.error(`Failed to bind SSH remote to host alias '${hostAlias}' at ${repoPath}`, error);
            return false;
        }
    }
}
